[package]
name = "hbs-cli"
version = "0.1.0"
authors = ["Jakub A. Gramsz <jakub@gramsz.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
handlebars = "2.0" # "3.0.0-beta.4"
serde = "1.0"
serde_yaml = "0.8"
